version: '2'
services:
    jhipster5react-app:
        image: jhipster5react
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster5react-mysql:3306/jhipster5react?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster5react-mysql:
        extends:
            file: mysql.yml
            service: jhipster5react-mysql
